# Generated by Django 5.0.6 on 2024-05-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0009_editlogs'),
        ('hris', '0010_employee_conducted_by_1_employee_conducted_by_2_and_more'),
    ]

    operations = [
    ]
